name: Java CI with Gradle

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_call:  # allow this workflow to be reused by others (like deploy)

permissions:
  contents: read

jobs:
  gradle_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21', '22', '23' ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build check

